### ISSUE TITLE
Error when migrating from Vue CLI to Vite: missing .vue extension in imports

### ISSUE THREAD

**Issue by acabreragnz** [mcibique/vue-headings#1]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vue-headings@1.0.0` for the project I'm working on.

I encountered an error while migrating from Vue CLI to Vite. The issue is that, by design, Vite requires the .vue extension in imports.
https://github.com/vitejs/vite/issues/178#issuecomment-630138450

![image](https://github.com/user-attachments/assets/24a2c102-73b0-4500-9d8c-3fcc63bffff4)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vue-headings/src/index.js b/node_modules/vue-headings/src/index.js
index 68ccde0..54375a3 100644
--- a/node_modules/vue-headings/src/index.js
+++ b/node_modules/vue-headings/src/index.js
@@ -1,2 +1,2 @@
-export { default as DocumentHeading } from "./document-heading";
-export { default as DocumentSection } from "./document-section";
+export { default as DocumentHeading } from "./document-heading.vue";
+export { default as DocumentSection } from "./document-section.vue";
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mcibique** [comment]
Hi, thanks for reporting :+1: . I have updated the imports and tested it with vite and vitest, should be all good now.

The fix has been released in 1.0.1.
